language: go

go:
  - 1.11.x

git:
  depth: 1

notifications:
  email: false

env:
  global:
    - NAME=docker-commander


matrix:
  include:
    # Linux
    - env: _GOOS=linux _GOARCH=amd64
      os: linux



install: true


