---

# docker run -it -d ubuntu

ubuntu: &ubuntu
  connect:
    from_image: ubuntu


config:

  - name: "group 1"
    config:

      - name: "command 1"
        exec:
          <<: *ubuntu
          cmd: ls -lah

  - name: "group 2"
    config:

      - name: "command 2"
        exec:
          <<: *ubuntu
          cmd: ls -lah /var
